name: CI
on:
  push:
    branches:
      - main
      - develop
env:
  NODE_VERSION: 16
  PNPM_VERSION: 7
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: pnpm/action-setup@v2
        with:
          version: ${{ env.PNPM_VERSION }}
      - uses: actions/setup-node@v2
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "pnpm"
      - run: pnpm install
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - run: pnpm build
      - name: Upload extension
        uses: actions/upload-artifact@v3
        with:
          name: swordev.phpstan.vsix
          path: "*.vsix"
      - name: Publish NPM package
        id: changesets
        uses: changesets/action@v1
        with:
          commit: "chore: update versions"
          title: Update versions
          publish: npx changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Build metadata
        id: metadata
        uses: actions/github-script@v5
        env:
          PUBLISHED_PACKAGES: ${{ steps.changesets.outputs.publishedPackages }}
        with:
          script: |
            const metadata = require('./.github/workflows/metadata.js')
            await metadata({ github, context, core })
      - name: Publish VSCode extension
        if: steps.metadata.outputs['publish'] == 'true'
        run: npx vsce publish
        env:
          VSCE_PAT: ${{secrets.VSCODE_MARKETPLACE_TOKEN}}
